version: '3.3'

services:

  ngx-alerts-demo:
    container_name: ngx-alerts-demo
    networks:
      - default
    build:
      context: ./
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ngx-alerts.rule=Host(`demo.mathijsblok.com`)"
      - "traefik.http.routers.ngx-alerts.entrypoints=https"
      - "traefik.http.routers.ngx-alerts.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ngx-alerts.middlewares=chain-no-auth@file"
      - "traefik.http.routers.ngx-alerts.service=ngx-alerts"
      - "traefik.http.services.ngx-alerts.loadbalancer.server.port=80"


networks:
  default:
    external:
      name: home-services_default

