version: '3.3'

services:

  ngx-alerts-demo:
    container_name: ngx-alerts-demo
    networks:
      - default
    build:
      context: ./
    restart: always
    environment:
      - VIRTUAL_HOST=demo.mathijsblok.com
      - LETSENCRYPT_HOST=demo.mathijsblok.com
      - LETSENCRYPT_EMAIL=info@mathijsblok.com
    labels:
      org.label-schema.group: "public"

networks:
  default:
    external:
      name: home-services_default

